### ISSUE TITLE
How to custom middleware?

### ISSUE THREAD

**Issue by blueway** [codeneomatrix/Merly.jl#10]
How to define a middleware?

**Comment by codeneomatrix** [comment]
exactly what do you want to do?

**Comment by codeneomatrix** [comment]
to use Mux.jl and similar ??

**Comment by blueway** [comment]
How to use Mux ?

**Comment by codeneomatrix** [comment]
You asked how to define a middleware, but I do not understand your question. do you mean to use mux in merly? or something like that?

**Comment by blueway** [comment]
ok,  how to use mux in merly?

**Comment by codeneomatrix** [comment]
it is possible to customize the message of not found, the headers, the status and the content of the answer, but nothing

**Comment by blueway** [comment]
Ok, thanks ,I will fork it or do it myself
