### ISSUE TITLE
"ERROR: UndefVarError: start not defined" with readme example

### ISSUE THREAD

**Issue by piruty** [codeneomatrix/Merly.jl#18]
**Describe the bug**
UndefVarError is thrown when running README Example.
`app = Merly.app(); app.start()` is working.
How can I use `start` method ?

**To Reproduce**

Run below on julia repl

```julia
using Merly

u="hello"

@page "/" "Hello World!"
@page "/hello/:usr>" "<b>Hello {{usr}}!</b>"

@route GET "/get/:data>" begin
  "get this back: {{data}}"
end

@route POST "/post" begin
  res.body = "I did something!"
end

@route POST|PUT|DELETE "/" begin
  println("params: ",req.params)
  println("query: ",req.query)
  println("body: ",req.body)

  res.headers["Content-Type"]= "text/plain"

  "I did something!"
end

Get("/data", (req,res)->(begin
  res.headers["Content-Type"]= "text/plain"
  u*"data"
end))


Post("/data", (req,res)->(begin
  println("params: ",req.params)
  println("query: ",req.query)
  println("body: ",req.body)
  res.headers["Content-Type"]= "text/plain"
  global u="bye"
  "I did something!"
end))


start(verbose = false)
```

**Expected behavior**
Run Merly app without Error.

**Environment**
- Julia: v1.5.0
 - OS: macOS v10.14.6
 - IDE: REPL

**Comment by codeneomatrix** [comment]
Thanks for the issue, if you use the version of the master branch, the start function works as follows: 

`start (host = "127.0.0.1", port = 8000, verbose = false)`

In version 0.2.1 it is used in the form: 

`app = Merly.app (); app.start (config = Dict ("host" => "127.0.0.1", "port" => 8000), verbose = false)`

**Comment by codeneomatrix** [comment]
This happens, because the package was created 2 years ago and the next version seeks to take advantage of the new features of the latest julia launches.

**Comment by piruty** [comment]
I reinstall Merly with master branch, `start` function works.
Thank you @codeneomatrix .
