### ISSUE TITLE
Benchmarks? 

### ISSUE THREAD

**Issue by polytomous** [codeneomatrix/Merly.jl#8]
This is an AWESOME project. Thank you so much for writing it! 👍  I just found it and ripped out some of the code to use in a similar julia microframework (with a radically different routing engine) 

Have you written any benchmarks for Merly's routing? If you haven't and I find some time, I'll try to share some back with you. If you're interested in working on that, we can pair program if you'd like. 😈

**Comment by codeneomatrix** [comment]
Hello thanks.
I have not done any benchmarks  I hope the release of version 7.0 to finish making more optimizations.
And of course I'm interested in working with you.
