### ISSUE TITLE
all request return NotFound

### ISSUE THREAD

**Issue by blueway** [codeneomatrix/Merly.jl#9]
all request return NotFound

julia-v0.7-rc2

**Comment by codeneomatrix** [comment]
thanks for the issue, I will solve it as soon as possible

**Comment by codeneomatrix** [comment]
I do not know the tests you did, but what probe works.

   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-rc2.0 (2018-08-02 19:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

**Comment by codeneomatrix** [comment]
![prueba](https://user-images.githubusercontent.com/8965843/43681953-cab29830-9828-11e8-9b4e-cc56f815be28.jpg)

**Comment by blueway** [comment]
julia> @page "/" "Hello World!"
ERROR: LoadError: UndefVarError: @page not defined
in expression starting at REPL[12]:1

**Comment by blueway** [comment]
Version 0.7.0-rc2.0 (2018-08-02 19:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  i686-pc-linux-gnu

**Comment by codeneomatrix** [comment]
using Merly

**Comment by blueway** [comment]
switch `using`, now working,  thanks,my problem
